// DO NOT MODIFY!
// Generated by mb-ormapper generator ver 2.2
// https://github.com/tmurakam/mb-ormapper

@import UIKit;

#import "ORRecord.h"

@class Asset;

NS_ASSUME_NONNULL_BEGIN

@interface AssetBase : ORRecord

@property(nonatomic,strong) NSString* name;
@property(nonatomic,assign) NSInteger type;
@property(nonatomic,assign) double initialBalance;
@property(nonatomic,assign) NSInteger sorder;
@property(nonatomic,strong) NSString* identifier;

+ (BOOL)migrate;

// CRUD (Create/Read/Update/Delete) operations

// Read operations (Finder)
+ (nullable Asset *)find:(NSInteger)pid;

+ (nullable Asset *)find_by_name:(NSString*)key cond:(nullable NSString*)cond;
+ (nullable Asset *)find_by_name:(NSString*)key;
+ (nullable Asset *)find_by_type:(NSInteger)key cond:(nullable NSString*)cond;
+ (nullable Asset *)find_by_type:(NSInteger)key;
+ (nullable Asset *)find_by_initialBalance:(double)key cond:(nullable NSString*)cond;
+ (nullable Asset *)find_by_initialBalance:(double)key;
+ (nullable Asset *)find_by_sorder:(NSInteger)key cond:(nullable NSString*)cond;
+ (nullable Asset *)find_by_sorder:(NSInteger)key;
+ (nullable Asset *)find_by_identifier:(NSString*)key cond:(nullable NSString*)cond;
+ (nullable Asset *)find_by_identifier:(NSString*)key;

+ (NSArray<Asset *> *)find_all:(nullable NSString *)cond;

+ (dbstmt *)gen_stmt:(nullable NSString *)cond;
+ (nullable Asset *)find_first_stmt:(dbstmt *)stmt;
+ (NSArray<Asset *> *)find_all_stmt:(dbstmt *)stmt;

// Delete operations
- (void)delete;
+ (void)delete_cond:(nullable NSString *)cond;
+ (void)delete_all;

// Dump SQL
+ (void)getTableSql:(NSMutableString *)s;
- (void)getInsertSql:(NSMutableString *)s;

@end

NS_ASSUME_NONNULL_END
