// DO NOT MODIFY!
// Generated by mb-ormapper generator ver 2.2
// https://github.com/tmurakam/mb-ormapper

#import <UIKit/UIKit.h>
#import "ORRecord.h"

@class DescLRU;

NS_ASSUME_NONNULL_BEGIN

@interface DescLRU : ORRecord

@property(nonatomic,strong) NSString* desc;
@property(nonatomic,strong) NSDate* lastUse;
@property(nonatomic,assign) NSInteger category;

+ (BOOL)migrate;

// CRUD (Create/Read/Update/Delete) operations

// Read operations (Finder)
+ (nullable DescLRU *)find:(NSInteger)pid;

+ (nullable DescLRU *)find_by_description:(NSString*)key cond:(nullable NSString*)cond;
+ (nullable DescLRU *)find_by_description:(NSString*)key;
+ (nullable DescLRU *)find_by_lastUse:(NSDate*)key cond:(nullable NSString*)cond;
+ (nullable DescLRU *)find_by_lastUse:(NSDate*)key;
+ (nullable DescLRU *)find_by_category:(NSInteger)key cond:(nullable NSString*)cond;
+ (nullable DescLRU *)find_by_category:(NSInteger)key;

+ (NSMutableArray<DescLRU *> *)find_all:(nullable NSString *)cond;

+ (dbstmt *)gen_stmt:(nullable NSString *)cond;
+ (nullable DescLRU *)find_first_stmt:(dbstmt *)stmt;
+ (NSMutableArray<DescLRU *> *)find_all_stmt:(dbstmt *)stmt;

// Delete operations
- (void)delete;
+ (void)delete_cond:(nullable NSString *)cond;
+ (void)delete_all;

// Dump SQL
+ (void)getTableSql:(NSMutableString *)s;
- (void)getInsertSql:(NSMutableString *)s;

@end

NS_ASSUME_NONNULL_END
