// DO NOT MODIFY!
// Generated by mb-ormapper generator ver 2.2
// https://github.com/tmurakam/mb-ormapper

#import <UIKit/UIKit.h>
#import "ORRecord.h"

@class TCategory;

NS_ASSUME_NONNULL_BEGIN

@interface TCategoryBase : ORRecord

@property(nonatomic,strong) NSString* name;
@property(nonatomic,assign) NSInteger sorder;

+ (BOOL)migrate;

// CRUD (Create/Read/Update/Delete) operations

// Read operations (Finder)
+ (nullable TCategory *)find:(NSInteger)pid;

+ (nullable TCategory *)find_by_name:(NSString*)key cond:(nullable NSString*)cond;
+ (nullable TCategory *)find_by_name:(NSString*)key;
+ (nullable TCategory *)find_by_sorder:(NSInteger)key cond:(nullable NSString*)cond;
+ (nullable TCategory *)find_by_sorder:(NSInteger)key;

+ (NSMutableArray<TCategory *> *)find_all:(nullable NSString *)cond;

+ (dbstmt *)gen_stmt:(nullable NSString *)cond;
+ (nullable TCategory *)find_first_stmt:(dbstmt *)stmt;
+ (NSMutableArray<TCategory *> *)find_all_stmt:(dbstmt *)stmt;

// Delete operations
- (void)delete;
+ (void)delete_cond:(nullable NSString *)cond;
+ (void)delete_all;

// Dump SQL
+ (void)getTableSql:(NSMutableString *)s;
- (void)getInsertSql:(NSMutableString *)s;

@end

NS_ASSUME_NONNULL_END
