// DO NOT MODIFY!
// Generated by mb-ormapper generator ver 2.3
// https://github.com/tmurakam/mb-ormapper

import Foundation

class TCategoryBase : ORRecord {

    var name : String = ""
    var sorder : Int = 0

    override init() {
        super.init()
    }

    /**
     @brief Migrate database table
     @return YES - table was newly created, NO - table already exists
     */
    class func migrate() -> Bool {
        let columnTypes: [String] = [
            "name", "TEXT",
            "sorder", "INTEGER",
        ]

        return super.migrate(columnTypes, primaryKey:"key")
    }

    // MARK: -  Read operations

    /**
      @brief get the record matchs the id
      @param pid Primary key of the record
      @return record
    */
    class func find(pid: Int) -> TCategory? {
        let db = Database.instance()

        let stmt = db.prepare("SELECT * FROM Categories WHERE key = ?;")
        stmt.bindInt(0, val: pid)

        return find_first_stmt(stmt)
    }

    /**
      finder with name

      @param key Key value
      @param cond Conditions (ORDER BY etc)
      @note If you specify WHERE conditions, you must start cond with "AND" keyword.
    */
    class func find_by_name(key: String, cond: String?) -> TCategory? {
        let cond2 = cond ?? ""
        let whr = "WHERE name = ? \(cond2) LIMIT 1"
        let stmt = gen_stmt(whr)
        stmt.bindString(0, val:key)
        return find_first_stmt(stmt)
    }

    class func find_by_name(key: String) -> TCategory? {
        return find_by_name(key, cond:nil)
    }

    /**
      finder with sorder

      @param key Key value
      @param cond Conditions (ORDER BY etc)
      @note If you specify WHERE conditions, you must start cond with "AND" keyword.
    */
    class func find_by_sorder(key: Int, cond: String?) -> TCategory? {
        let cond2 = cond ?? ""
        let whr = "WHERE sorder = ? \(cond2) LIMIT 1"
        let stmt = gen_stmt(whr)
        stmt.bindInt(0, val:key)
        return find_first_stmt(stmt)
    }

    class func find_by_sorder(key: Int) -> TCategory? {
        return find_by_sorder(key, cond:nil)
    }


    /**
      Get first record matches the conditions
      @param cond Conditions (WHERE phrase and so on)
      @return array of records
    */
    class func find_first(cond: String?) -> TCategory? {
        let cond2: String
        if (cond == nil) {
            cond2 = "LIMIT 1"
        } else {
            cond2 = cond! + " LIMIT 1"
        }
        let stmt = gen_stmt(cond2)
        return  find_first_stmt(stmt)
    }

    /**
      Get all records match the conditions
      @param cond Conditions (WHERE phrase and so on)
      @return array of records
    */
    class func find_all(cond: String?) -> [TCategory] {
        let stmt = gen_stmt(cond)
        return find_all_stmt(stmt)
    }

    /**
      create dbstmt
      @param s condition
      @return dbstmt
    */
    class func gen_stmt(cond: String?) -> dbstmt {
        let sql: String
        if (cond == nil) {
            sql = "SELECT * FROM Categories;"
        } else {
            sql = "SELECT * FROM Categories \(cond!);"
        }  
        let stmt = Database.instance().prepare(sql)
        return stmt
    }

    /**
      Get first record matches the conditions
      @param stmt Statement
      @return array of records
    */
    class func find_first_stmt(stmt: dbstmt) -> TCategory? {
        if (stmt.step() == numericCast(SQLITE_ROW)) {
            // e = [[self class] new]
            let e = TCategory()
            e._loadRow(stmt)
            return e
        }
        return nil;
    }

    /**
      Get all records match the conditions
      @param stmt Statement
      @return array of records
    */
    class func find_all_stmt(stmt: dbstmt) -> [TCategory] {
        var array : [TCategory] = []

        while (stmt.step() == numericCast(SQLITE_ROW)) {
            //let e = self.class().new()
            let e = TCategory()
            e._loadRow(stmt)
            array.append(e)
        }
        return array;
    }

    override func _loadRow(stmt: dbstmt) {
        self.pid = stmt.colInt(0)
        self.name = stmt.colString(1)
        self.sorder = stmt.colInt(2)
    }

    // MARK: - Create operations

    override func _insert() {
        super._insert()

        let db = Database.instance()
    
        //db.beginTransaction()
        let stmt = db.prepare("INSERT INTO Categories VALUES(NULL,?,?);")
        stmt.bindString(0, val:self.name)
        stmt.bindInt(1, val:self.sorder)
        stmt.step()

        self.pid = db.lastInsertRowId

        //db.commitTransaction()

        db.setModified()
    }

    // MARK: - Update operations

    override func _update() {
        super._update()

        let db = Database.instance()
        //db.beginTransaction()

        let stmt = db.prepare("UPDATE Categories SET "
        + "name = ?"
        + ",sorder = ?"
        + " WHERE key = ?;")
        stmt.bindString(0, val:self.name)
        stmt.bindInt(1, val:self.sorder)
        stmt.bindInt(2, val:self.pid)

        stmt.step()
        //db.commitTransaction()

        db.setModified()
    }

    // MARK: - Delete operations

    /**
      Delete record
    */
    override func delete() {
        let db = Database.instance()

        let stmt = db.prepare("DELETE FROM Categories WHERE key = ?;")
        stmt.bindInt(0, val:self.pid)
        stmt.step()

        db.setModified()
    }

    /**
     Delete all records
    */
    class func delete_cond(cond: String?) {
        let db = Database.instance()

        let cond2: String
        if (cond == nil) {
            cond2 = ""
        } else {
            cond2 = cond!
        }
        let sql = "DELETE FROM Categories \(cond2);"
        db.exec(sql)

        db.setModified()
    }

    override class func delete_all() {
        TCategoryBase.delete_cond(nil)
    }

    /**
     * get table sql
     */
    class func getTableSql(s: NSMutableString) {
        s.appendString("DROP TABLE Categories;\n")
        s.appendString("CREATE TABLE Categories (key INTEGER PRIMARY KEY")

        s.appendString(", name TEXT")
        s.appendString(", sorder INTEGER")
    
        s.appendString(");\n")

        let ary = find_all(nil)
        for e in ary {
            e.getInsertSql(s)
            s.appendString("\n")
        }
    }

    /**
     * get "INSERT" SQL
     */
    func getInsertSql(s: NSMutableString) {
        s.appendFormat("INSERT INTO Categories VALUES(%ld", self.pid)
        s.appendString(",")
        s.appendString(quoteSqlString(name))
        s.appendString(",")
        s.appendString(quoteSqlString(sorder.description))
        s.appendString(");")
    }

    // MARK: - Internal functions

    override class func tableName() -> String {
        return "Categories"
    }
}
